### ISSUE TITLE
analytical solutions for standard models

### ISSUE THREAD

**Issue by vjd** [PumasAI/Pumas.jl#275]
bumping this up for anyone who can finish the standard analytical solutions for 1,2,3 compartment models with and without steady-state.

**Comment by ChrisRackauckas** [comment]
What are the ODEs you want to see an analytical solution for, and what names should they go under?

**Comment by andreasnoack** [comment]
Maybe we can use http://www.pfim.biostat.fr/PFIM_PKPD_library.pdf as inspiration for which models to cover and what to call them.

**Comment by andreasnoack** [comment]
This was fixed in #740. We can open individual issue if other models need to be implemented.
