### ISSUE TITLE
Bayesian tests are unpredictable

### ISSUE THREAD

**Issue by ChrisRackauckas** [PumasAI/Pumas.jl#344]
Tracking https://github.com/tpapp/DynamicHMC.jl/issues/38 . I went through a bunch of previous masters and found my laptop always failed because some theta was off by too much, my workstation failed because of these epsilon errors, and of course Travis passed. But now Travis failed with the epsilon errors, and whether these are passing/failing based on numbers or epsilon error depends on the random seed that is chosen and what tests were ran before. I attempted to make it "Travis-safe", so it would run and if it hits the epsilon error it would just continue, so that way the test doesn't have to be completely disabled while we wait on https://github.com/tpapp/DynamicHMC.jl/issues/39 as a possible fix.

**Comment by tpapp** [comment]
I would really love to address this in the upcoming refactor of DynamicHMC (https://github.com/tpapp/DynamicHMC.jl/pull/44), so if you have an MWE, or even just some code I can run, please let me know where to start.

**Comment by ChrisRackauckas** [comment]
This is actually fixed by a switch to AdvancedHMC.jl. However, tests of the same phenomena still exist in the ecosystem as https://github.com/JuliaDiffEq/DiffEqBayes.jl/blob/master/test/dynamicHMC.jl which is the basis for https://github.com/tpapp/DynamicHMC.jl/issues/38 and fails most tests since the v1.0 update.

Closing due to https://github.com/PumasAI/Pumas.jl/pull/601
