### ISSUE TITLE
Multiple observations and random effects

### ISSUE THREAD

**Issue by ChrisRackauckas** [PumasAI/Pumas.jl#346]
`@derived` can return more than one series of observations, and `@random` can have more than one random effect. Right now, the likelihood functions are hardcoded to `.dv` for observations and `.η` for random effects. The FIM calculations like the stuff in

https://github.com/UMCTM/PuMaS.jl/blob/master/src/estimation/likelihoods.jl#L343
https://github.com/UMCTM/PuMaS.jl/blob/master/src/estimation/likelihoods.jl#L359

should be extended to use `getproperty` of the named tuple. `ll_derivatives` should take the derivative w.r.t. each component, and @jony5525 I believe the FIM ends up being the block FIM of these?

The diagnostics all need to be handled as well:

https://github.com/UMCTM/PuMaS.jl/blob/master/src/estimation/diagnostics.jl#L2

**Comment by pkofod** [comment]
this will be fixed by https://github.com/PumasAI/Pumas.jl/pull/696

**Comment by andreasnoack** [comment]
This has been fixed.
