### ISSUE TITLE
marginal_nll_nonmem on ragged

### ISSUE THREAD

**Issue by ChrisRackauckas** [PumasAI/Pumas.jl#348]
We can use a double sum here:

https://github.com/UMCTM/PuMaS.jl/pull/342/files/ab9de3a0890d16414355ea0107adf16943b305c9#diff-12cf2a8404230fb7864c9adfb5706121R297

but since this is just for regression tests against NONMEM which doesn't allow this raggedness, it's a detail that was skipped over for now.

**Comment by pkofod** [comment]
Function no longer exists
