### ISSUE TITLE
error `First function call produced NaNs`

### ISSUE THREAD

**Issue by walsu** [PumasAI/Pumas.jl#387]
I'm trying to estimate parameter with 2-compartment oral absorption model.
This is multiple dose data (addl 4, ii 24). 
CMT is set as 1 for dosing event and as 2 for observation event.
It works in NONMEM but I got an error 'First function call produced NANs. Exiting.' in PuMaS.

**Comment by andreasnoack** [comment]
I don't think this is a problem anymore. Please leave a comment here in case it is and we'll reopen.
