### ISSUE TITLE
Throw or warn when time is missing

### ISSUE THREAD

**Issue by andreasnoack** [PumasAI/Pumas.jl#389]
Initially when #387  was reported, the dataset contained a variable named `timd` instead of `time`. this cause an error during the likelihood computation. Ideally, this should be detected earlier. Not sure exactly where we'd like to warn or throw if a dataset doesn't have a time variable. Maybe we want to allow no time variable if there is only a single observation but then we should probably warn/throw when there is more than a single observation per subject.

**Comment by pkofod** [comment]
Superseded by #864 because that covers checking if input is in dataframe
