### ISSUE TITLE
 time instead of using all subject.time parsing for time varying covariates

### ISSUE THREAD

**Issue by vjd** [PumasAI/Pumas.jl#409]
looks like parsing time-varying covariates in `process_nmtran` is not correct. #44 talks about this issue and in PR https://github.com/UMCTM/PuMaS.jl/pull/406

**Comment by andreasnoack** [comment]
@vjd Is this still an issue?

**Comment by vjd** [comment]
I don't think so as we changed the internal representation of  `tvcov`
