### ISSUE TITLE
fit single subject data

### ISSUE THREAD

**Issue by vjd** [PumasAI/Pumas.jl#510]
using any of the theophylline tests, can we fit data only for a single subject? So, no mixed effects, only the population parameters that define the analytical solution and perhaps the error model but no `omegas`?

`single = fit(theopmodel_focei, theopp[1], param, PuMaS.FOCEI())`

what needs to be done to make this work?
1. fix `omega` to zero?
2. remove `omega` and `@random` from the model and hence all the `etas` in the `@pre`?

**Comment by pkofod** [comment]
What would the point of the last positional argument be here? That's not supposed to be there right?

**Comment by andreasnoack** [comment]
Right. I think the `fit` signature for `Subject` shouldn't have a `LikelihoodApproximation` argument.

**Comment by pkofod** [comment]
Right, so for a single Subject that should probably error. If you want to do something like `TwoStage()` or `NaivePooled()` they would just go there, but require a `Population` and not just a `Subject`.

(this is just me saying my plans out loud, but please criticize if you disagree)
