### ISSUE TITLE
Optim is sensitive to the source of ODE solutions

### ISSUE THREAD

**Issue by vjd** [PumasAI/Pumas.jl#602]
This is linked to #600 For the model given below, the default `alg=AutoTsit5(Rosenbrock23())`  is not stable during optimization.  Switching to `alg=Rosenbrock23()` allows it to converge. Needs an evaluation of the algorithm.
dataset - [SCM_Mutaz.xlsx](https://github.com/PumasAI/Pumas.jl/files/3438258/SCM_Mutaz.xlsx)

```julia
using Pumas, CSV

data = CSV.read("SCM_Mutaz.csv")

data = read_pumas(data, cvs =[:WT],
        dvs = [:dv], id=:ID, time=:TIME,
        evid=:EVID,amt=:AMT,cmt=:CMT,event_data=true)

mod = @model begin
  @param   begin
    tvcl ∈ RealDomain(lower=0, init = 4)
    tvv ∈ RealDomain(lower=0, init = 10)
    tvka ∈ RealDomain(lower = 0, init= 1.5)
    Ω ∈ PDiagDomain(init=[0.09,0.09,0.09])
    σ_prop ∈ RealDomain(lower=0,init=0.02)
  end

  @random begin
    η ~ MvNormal(Ω)
  end
  @covariates WT
  @pre begin
    CL = tvcl  * exp(η[1])
    V  = tvv   * exp(η[2])
    Ka = tvka * exp(η[3])
  end

  #@dynamics OneCompartmentModel
  @dynamics begin
    Depot' =  -Ka*Depot
    Central' =  Ka*Depot - (CL/V)*Central
  end

  @derived begin
      cp = @. (Central / V)
      dv ~ @. Normal(cp, sqrt(cp^2*σ_prop))
    end
end


param = init_param(mod)
f1 = fit(mod, data, param, Pumas.FOCEI())

```

**Comment by ChrisRackauckas** [comment]
Yes, we need to checking the switching parameters and make it a little more sensitive.

**Comment by YingboMa** [comment]
I am not sure if that is a problem with the switching algorithm. Using `TRBDF2` or `Rodas5` which are L-stable algorithms fail to converge, too.

**Comment by YingboMa** [comment]
Every solve was completed successfully, but Optim was not able to converge.
```julia
 ┌ Warning: Linesearch failed, using alpha = 0.0 and exiting optimization.
│ The linesearch exited with message:
│ Linesearch failed to converge, reached maximum iterations 1000.
└ @ Optim ~/.julia/packages/Optim/Agd3B/src/utilities/perform_linesearch.jl:47
```

The fact that `Rosenbrock23` worked is just a coincidence.

@pkofod could you take a look?

**Comment by pkofod** [comment]
Yes. I wonder if it converges if you adjust the tolerance to solve at higher precision cf Andreas' and my previous experience.

**Comment by andreasnoack** [comment]
> I wonder if it converges if you adjust the tolerance to solve at higher precision cf Andreas' and my previous experience.

Indeed it does with `reltol=1e-12`.

I think that NONMEM might often terminate the optimization with failed line search. Their criterion is the relative change to the parameters which goes to zero as the step size decreases. In the current version in JuliaPro, we report a warning but that might not be the case in the future. You'd still be able to see the termination details from the optim object but the warning shouldn't be printed.

However, we might still be able to do better here. I think we are still in some cases taking too small step sizes when computing the finite differences for ODE solver based models. I'll take a look once I'm done with some other tasks.

**Comment by pkofod** [comment]
Then, I think the good thing to note here is that Andreas and I have a pretty good understanding of the problem, but the heuristics just aren't there yet.

**Comment by vjd** [comment]
@pkofod just bumping this issue up so that we can get this sorted out wrt next steps.

**Comment by ChrisRackauckas** [comment]
Idea to try: instead of AD, switch it all to DoubleFloats.jl. That should have low enough truncation errors. Are the derivatives all the same? There is a chance it could be AD issues.

**Comment by andreasnoack** [comment]
See https://github.com/PumasAI/Pumas.jl/issues/602#issuecomment-516298931

**Comment by pkofod** [comment]
>  just bumping this issue up so that we can get this sorted out wrt next steps.

I'm willing to bet real money that we could solve most of these issues by solving the ODEs to a tighter tolerance, but that'll come at a significant cost in all the "nice" cases. If we have a list of problems/datasets where this has occured, we can substantiate that conjecture, but I'm quite certain.

**Comment by ChrisRackauckas** [comment]
Is it the jumpy behavior for changes in adaptivity that cause the problem in the line search? The adaptivity gives the solution leeway to have differences around the order of the tolerance, so two solutions with tolerance 1e-6 could be 1e-6 apart at the same point with very similar parameters. I would assume the line search would be robust to that sort of thing though if the line search tolerance is higher than the ODE solver tolerance (by at least 10)?

**Comment by pkofod** [comment]
<img width="1244" alt="Screen Shot 2019-07-02 at 11 00 25" src="https://user-images.githubusercontent.com/8431156/63291156-47c4c580-c2c3-11e9-868a-922571fa7f3c.png">

(stolen from andreas)

This is the likelihood contribution for some subject with constant fixed effects but varying eta (hence the centering around 0). `reltol` is the `reltol` passed onto the ode solver. As you can see this has nothing to do with AD or derivatives at all, it's the objective itself that is wonky! Note, this is how it looks in the cases where it goes wrong. For "normal"/"good" cases, the wonky-ness is much much less pronounced. The problematic cases just end up ruining the whole iteration. Start anywhere on that x-axis and it'll be hard to find a step that decreases the function in any systematic way. Note also that the solution for `reltol=1e-6` is quite far away from the actual solution!

**Comment by ChrisRackauckas** [comment]
>Note also that the solution for reltol=1e-6 is quite far away from the actual solution!

It's getting the 6th digit incorrect, which is what was asked for 🤷‍♂ . But yes, the question is whether there is a line search that is robust to the fact that it doesn't care about that 6th digit if you want reltol=1e-6. In the grand scheme of the optimization, those fluctuations are still "small", but I could see it causing numerical difficulties.

**Comment by pkofod** [comment]
> It's getting to the 6th digit incorrect, which is what was asked for

That's not what I meant though. I mean that the likelihood function as drawn using a 1e-6 solution is very imprecise, I'm not saying the ODE solution is wrong, I'm saying that that tolerance is not sufficient to evaluate this particular likelihood contribution.

> But yes, the question is whether there is a line search that is robust to the fact that it doesn't care about that 6th digit if you want reltol=1e-6.

This is the problem I'm trying to articulate: It's not the line search, it's the fact that the likelihood function evaluation is not precise enough (for this particular parameter vector) to meaningfully act as if we're getting the actual value back. That's why I'm saying: from a point of view of optimizing the likelihood function it's better the more precise the solution. `reltol=1e-6` might not be too low for solving and simulating from the model and looking at those, but clearly it's not enough here (not in *all* situations mind you, I'm not denying that it might suffice in the nicer regions of the parameter space) to meaningfully optimize this with a algorithm that assumes smoothness (and differentiability) in the parameters (in this region of parameter space).

One could then say: okay, we just use a global method that can find the minimum even if it's wonky. That's fine, but probably a lot slower in the nicer regions. All I'm saying is that I'd bet that setting that tolerance to 1e-8 or even lower is what it takes for the problematic cases to go through for 99.99% of the cases that have been, and will be in the future, reported with this problem. So at the very least, if we're not willing to take that performance penalty, we should document that if you run into problems like these, you should try decreasing reltol as a first step. Or make something more adaptive where a very low negative log-likelihood value solution should have it's solution refined to verify the precision.

It's also quite possible that some of this will go away if we allow for `init_param` to be generated by a naive pooled estimate or similar. Simply because you're avoiding weird parameters.

**Comment by ChrisRackauckas** [comment]
>It's also quite possible that some of this will go away if we allow for init_param to be generated by a naive pooled estimate or similar. 

We should do something like that.

>One could then say: okay, we just use a global method that can find the minimum even if it's wonky. That's fine, but probably a lot slower in the nicer regions. All I'm saying is that I'd bet that setting that tolerance to 1e-8 or even lower is what it takes for the problematic cases to go through for 99.99% of the cases that have been, and will be in the future, reported with this problem. So at the very least, if we're not willing to take that performance penalty, we should document that if you run into problems like these, you should try decreasing reltol as a first step. Or make something more adaptive where a very low negative log-likelihood value solution should have it's solution refined to verify the precision.

Okay, then let's set the estimation defaults differently from simulation. `AutoVern7(Rodas5())` with `1e-8'`s?

**Comment by pkofod** [comment]
> Okay, then let's set the estimation defaults differently from simulation. `AutoVern7(Rodas5())` with `1e-8'`s?

I'll give it a spin.

**Comment by pkofod** [comment]
I tried the problem above. With the defaults it fails at iteration 43, with reltol =1e-8 and the default solvers it converges and with reltol=1e-8 and AutoVern7(Rodas5()) it converges and appears to be the fastest of the two for this particular problem. We need to look a bit more into it before we change the defaults though I think.

**Comment by andreasnoack** [comment]
The other issue is that, sometimes, the direction is not descending. I think I'd have to adjust the finite difference stepsize in some cases.

**Comment by pkofod** [comment]
In any case it doesn’t make sense to FD something as noisy as the worst case in the plot above. Does the descent direction thing happen even when there aren’t extreme subject fits?

**Comment by andreasnoack** [comment]
On latest master of Pumas, this is failing with
```julia
    43    -1.922743e+03     1.435200e+00
 * Current step size: 1.7046684590346216e-7
 * time: 91.35555505752563
 * g(x): [-0.9530596736825774, 0.32065568057256755, -1.435199634649865, 0.005200502778008931, 0.008372366004182563, 0.059859194970393076, -0.05105057339855068]
 * ~inv(H): [257.9864326531004 -239.91135620939235 147.09854534991328 5.3024735816945405 1.5490153191727292 -8.94838256114432 0.6246297503864451; -239.91135620939235 224.23015884444132 -137.49499707125483 -4.93565186197346 -1.4393708360312554 8.354222912319287 -0.6001486921313; 147.0985453499133 -137.49499707125483 84.31371142954198 3.0458687183441104 0.8936854654723813 -5.101170582259751 0.3294492478221894; 5.302473581694541 -4.935651861973461 3.045868718344111 0.8230480827479649 0.03170203824478302 -0.18485284552416417 0.013646550407970878; 1.5490153191727292 -1.4393708360312554 0.8936854654723813 0.031702038244783015 0.7233555174976165 -0.05411801024338315 0.004199730515377181; -8.948382561144323 8.354222912319287 -5.101170582259751 -0.18485284552416414 -0.054118010243383155 1.0249412849638966 -0.02089495384094166; 0.6246297503864451 -0.6001486921313 0.3294492478221894 0.013646550407970878 0.004199730515377181 -0.02089495384094166 0.7141567648366705]
 * x: [3.4271455639050994, 2.99427887621422, 0.1691235613070558, -2.806623686775703, -2.1992936568109385, -3.5422329060249806, -3.7638927613785405]
ERROR: First function call produced NaNs. Exiting.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] ode_determine_initdt(::LabelledArrays.SLArray{Tuple{2},Float64,1,2,(:Depot, :Central)}, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::typeof(DiffEqBase.ODE_DEFAULT_NORM), ::ODEProblem{LabelledArrays.SLArray{Tuple{2},Float64,1,2,(:Depot, :Central)},Tuple{Float64,Float64},false,NamedTuple{(:CL, :V, :Ka, :tvcl, :tvv, :tvka, :Ω, :σ_prop, :η, :WT),Tuple{Float64,Float64,Float64,Float64,Float64,Float64,PDMats.PDiagMat{Float64,Array{Float64,1}},Float64,Array{Float64,1},Float64}},ODEFunction{false,Pumas.DiffEqWrapper{getfield(ModelingToolkit, Symbol("#out_f_safe#66")){getfield(ModelingToolkit, Symbol("###766"))},LabelledArrays.SLArray{Tuple{2},Float64,1,2,(:Depot, :Central)}},LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},CallbackSet{Tuple{},Tuple{DiscreteCallback{getfield(Pumas, Symbol("#condition#424")){Array{Float64,1},Base.RefValue{Bool},Base.RefValue{Float64},Base.RefValue{Float64},Base.RefValue{Float64},
```
on my machine. @vjd Is that the same error you are currently getting?

@ChrisRackauckas We have discussed this one before. Would it be possible for DiffEq to return an error code here instead of throwing?

**Comment by ChrisRackauckas** [comment]
That now returns an error code with the newest OrdinaryDiffEq+DiffEqBase patches.

**Comment by andreasnoack** [comment]
Just tried this out. It doesn't look like it solves theproblem. It avoids the exception but the optimization seems to be stuck in an area where the default solver keeps complaining. I tried `Rosenbrock23`, `Vren7`, `TRBDF2`, and `Rodas5` with the default tolerances. They all succeeded so maybe there something about `Tsit5` that doesn't work well with optimization.

**Comment by ChrisRackauckas** [comment]
This specific case was fixed by https://github.com/PumasAI/Pumas.jl/pull/650 . We can open a new issue for any new ones that come up.
