### ISSUE TITLE
Fully commit to Markdown stdlib?

### ISSUE THREAD

**Issue by asinghvi17** [PumasAI/Pumas.jl#618]
https://github.com/PumasAI/Pumas.jl/blob/8356a61bf648206c2de17ca77487fcebeefb0402/src/nca/type.jl#L456

This prints out Markdown and then parses it.  Would it not be better to use Markdown type constructors (`Table` et al) to do this instead?

**Comment by ChrisRackauckas** [comment]
It would be better to just use the Markdown type constructors.

**Comment by asinghvi17** [comment]
I meant within the convert function.

**Comment by YingboMa** [comment]
That function is not actually used, though.

**Comment by asinghvi17** [comment]
https://github.com/PumasAI/Pumas.jl/blob/8356a61bf648206c2de17ca77487fcebeefb0402/src/nca/type.jl#L455-L456

was what I was thinking of - you could construct headers using `Markdown.Header`, tables using `Markdown.Table`, etc.

**Comment by YingboMa** [comment]
Currently, we don't try to generate a Markdown report, and this function is not documented either.
