### ISSUE TITLE
Bolus tests of proportional+additive model with FOCE sometimes causes NaNs

### ISSUE THREAD

**Issue by andreasnoack** [PumasAI/Pumas.jl#761]
See e.g. https://gitlab.com/PumasAI/Pumas-jl/-/jobs/362664512. This only happens on come machine but unfortunately one of the machine is the CI machine and it results in very slow completion times for the tests. We suspect the issue is related to the use of the `DiffEqBase.fastpow`, see https://github.com/PumasAI/Pumas.jl/pull/736. Switching to e.g. `Tsit5()` instead of the default solver also seems to avoid the issue.

**Comment by ChrisRackauckas** [comment]
Well this is quite interesting because it means it's not fastpow, but rather an interaction with the switching mechanism. @YingboMa that's a good hint.

**Comment by andreasnoack** [comment]
This model is no longer supported so closing.
