### ISSUE TITLE
Length of all observations and time should be equal in Subject

### ISSUE THREAD

**Issue by andreasnoack** [PumasAI/Pumas.jl#771]
```julia
julia> Subject(obs=(dv=[1.0,2,3],)).time === nothing
true
```
which is an unintended consequence of the change of storage representation we made in the spring. The `Subject` constructor should require that the `time` vector matches the observations.

**Comment by ChrisRackauckas** [comment]
No it shouldn't because that won't be the case in many models. For example, scalar observations are fine.

**Comment by ChrisRackauckas** [comment]
Weird types as observations are also fine. It's just a thing from the CSVs.

**Comment by andreasnoack** [comment]
Generally, I think it would be a useful consistency check to require this. You can always set the time vector to `[0.0]` if you just have a single observation per subject. If we really do want to allow for purely cross sectional data then we should add some other checks, e.g. that all observations are scalars when time is missing. We might also have to add other kinds of checks in various places if we cannot assume that the lengths are the same.

**Comment by ChrisRackauckas** [comment]
That answer didn't address the real issue. A "consistency check" for this would incorrectly require that it's "consistent" which is the issue.

**Comment by andreasnoack** [comment]
So are you arguing that `Subject(obs=(dv=[1.0, 2.0, 3.0],))` should allowed e.g. for model that would like to consider `[1.0, 2.0, 3.0]` just a single observation? I think that would make it harder to provide useful error checks.

**Comment by ChrisRackauckas** [comment]
`Subject(obs=(dv=[1.0, 2.0, 3.0],auc=5.0,))`

**Comment by ChrisRackauckas** [comment]
Closing because it would break round-trippability and examples like the one posted above, among other things, which is why we stopped enforcing it in the first place.

**Comment by andreasnoack** [comment]
I think we need to figure out what we should require from the different fields in order to have a meaningful structure. Allowing e.g.
 ```julia
julia> Subject(obs=(dv1 = [1.0, 2.0, 3.0], dv2 = [1.0, 2.0]), time = [1.0])
Subject
  ID: 1
  Events: 0
  Observables: dv1: (n=3), dv2: (n=2)
```
doesn't seem sensible so let's discuss this and close once the issue once we have reached a common understanding of the how a `Subject` should behave.
