### ISSUE TITLE
Unable to install Pumas for a few weeks now

### ISSUE THREAD

**Issue by tszanalytics** [PumasAI/Pumas.jl#774]
We have been unable to install Pumas.jl having tried several times over the last few weeks.  

using
]add Pumas
leads to the error:
ERROR: The following package names could not be resolved:
 * Pumas (not found in project, manifest or registry)
Please specify by known `name=uuid`.

When I try
]add https://github.com/PumasAI/Pumas.jl.git
I get incompatible dependency errors.  After trying several different ways and attempting to reinstall package dependencies, the error message I'm left with is:

ERROR: Unsatisfiable requirements detected for package ModelingToolkit [961ee093]:
 ModelingToolkit [961ee093] log:
 ├─possible versions are: [0.0.1-0.0.2, 0.1.0, 0.2.0, 0.4.0, 0.5.0, 0.6.0-0.6.1, 0.6.3-0.6.4, 0.7.0-0.7.2, 0.8.0, 0.9.0-0.9.1, 0.10.0, 1.0.0] or uninstalled
 ├─restricted to versions 1.0.0-1 by Pumas [4f2c3c20], leaving only versions 1.0.0
 │ └─Pumas [4f2c3c20] log:
 │   ├─possible versions are: 0.7.0 or uninstalled
 │   └─Pumas [4f2c3c20] is fixed to version 0.7.0
 └─restricted by compatibility requirements with DiffRules [b552c78f] to versions: [0.0.1-0.0.2, 0.1.0, 0.2.0, 0.4.0, 0.5.0, 0.6.0-0.6.1, 0.6.3-0.6.4, 0.7.0-0.7.2, 0.8.0] or uninstalled — no versions left
   └─DiffRules [b552c78f] log:
     ├─possible versions are: [0.0.8-0.0.10, 0.1.0] or uninstalled
     └─restricted to versions 0.0.10 by an explicit requirement, leaving only versions 0.0.10

**Comment by ChrisRackauckas** [comment]
Is this on JuliaPro?

**Comment by tszanalytics** [comment]
Nope.  I tried using juno and using just the REPL on two different machines
and received the same error.

Best,
Jeff

**Comment by andreasnoack** [comment]
Pumas is distributed only through the JuliaPro registry so you'd have to install JuliaPro to use it.

**Comment by tszanalytics** [comment]
Ok, guess I will have to install that.  Thanks!
