### ISSUE TITLE
Installed Pumas with juliapro - get the following error

### ISSUE THREAD

**Issue by tszanalytics** [PumasAI/Pumas.jl#799]
So I went through the pain and suffering of installing JuliaPro just so I can use Pumas, and I get the following error:
```julia
julia> using Pumas
[ Info: Precompiling Pumas [4f2c3c20-a4ac-11e9-067b-e5872d3484cf]
WARNING: could not import LogDensityProblems.AbstractLogDensityProblem into Pumas
ERROR: LoadError: LoadError: UndefVarError: AbstractLogDensityProblem not defined
Stacktrace:
 [1] getproperty(::Module, ::Symbol) at .\Base.jl:13
 [2] top-level scope at C:\Users\millsjf\.juliapro\JuliaPro_v1.2.0-1\packages\Pumas\0iiH8\src\estimation\bayes.jl:18
 [3] include at .\boot.jl:328 [inlined]
 [4] include_relative(::Module, ::String) at .\loading.jl:1094
 [5] include at .\Base.jl:31 [inlined]
 [6] include(::String) at C:\Users\millsjf\.juliapro\JuliaPro_v1.2.0-1\packages\Pumas\0iiH8\src\Pumas.jl:1
 [7] top-level scope at C:\Users\millsjf\.juliapro\JuliaPro_v1.2.0-1\packages\Pumas\0iiH8\src\Pumas.jl:31
 [8] include at .\boot.jl:328 [inlined]
 [9] include_relative(::Module, ::String) at .\loading.jl:1094
 [10] include(::Module, ::String) at .\Base.jl:31
 [11] top-level scope at none:2
 [12] eval at .\boot.jl:330 [inlined]
 [13] eval(::Expr) at .\client.jl:432
 [14] top-level scope at .\none:3
in expression starting at C:\Users\millsjf\.juliapro\JuliaPro_v1.2.0-1\packages\Pumas\0iiH8\src\estimation\bayes.jl:18
in expression starting at C:\Users\millsjf\.juliapro\JuliaPro_v1.2.0-1\packages\Pumas\0iiH8\src\Pumas.jl:31
ERROR: Failed to precompile Pumas [4f2c3c20-a4ac-11e9-067b-e5872d3484cf] to C:\Users\millsjf\.juliapro\JuliaPro_v1.2.0-1\compiled\v1.2\Pumas\OjQAZ.ji.
Stacktrace:
 [1] compilecache(::Base.PkgId, ::String) at .\loading.jl:1253
 [2] _require(::Base.PkgId) at .\loading.jl:1013
 [3] require(::Base.PkgId) at .\loading.jl:911
 [4] require(::Module, ::Symbol) at .\loading.jl:906
```
I would really like to be able to use Pumas again (it was working a while ago just by adding as a regular package), so any help appreciated.

Thanks.

**Comment by andreasnoack** [comment]
Hm. The error message indicates that it's an old version of Pumas. What do you get from `] st Pumas`? You could also try `] up Pumas` and let us know the result.

**Comment by tszanalytics** [comment]
Here the status and update:

Starting Julia...
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.2.0 (2019-08-20)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(v1.2) pkg> st Pumas
    Status
`C:\Users\millsjf\.juliapro\JuliaPro_v1.2.0-1\environments\v1.2\Project.toml`
  [336ed68f] CSV v0.5.18
  [a93c6f00] DataFrames v0.19.4
  [31c24e10] Distributions v0.21.10
  [4f2c3c20] Pumas v0.0.7
  [37e2e46d] LinearAlgebra

(v1.2) pkg> up Pumas
  Updating registry at
`C:\Users\millsjf\.juliapro\JuliaPro_v1.2.0-1\registries\JuliaPro`
  Updating git-repo `https://pkg.juliacomputing.com//registry/JuliaPro`
 Resolving package versions...
  Updating
`C:\Users\millsjf\.juliapro\JuliaPro_v1.2.0-1\environments\v1.2\Project.toml`
 [no changes]
  Updating
`C:\Users\millsjf\.juliapro\JuliaPro_v1.2.0-1\environments\v1.2\Manifest.toml`
 [no changes]

julia> using Pumas
[ Info: Precompiling Pumas [4f2c3c20-a4ac-11e9-067b-e5872d3484cf]
WARNING: could not import LogDensityProblems.AbstractLogDensityProblem into
Pumas
ERROR: LoadError: LoadError: UndefVarError: AbstractLogDensityProblem not
defined
Stacktrace:
 [1] getproperty(::Module, ::Symbol) at .\Base.jl:13
 [2] top-level scope at
C:\Users\millsjf\.juliapro\JuliaPro_v1.2.0-1\packages\Pumas\0iiH8\src\estimation\bayes.jl:18
 [3] include at .\boot.jl:328 [inlined]
 [4] include_relative(::Module, ::String) at .\loading.jl:1094
 [5] include at .\Base.jl:31 [inlined]
 [6] include(::String) at
C:\Users\millsjf\.juliapro\JuliaPro_v1.2.0-1\packages\Pumas\0iiH8\src\Pumas.jl:1
 [7] top-level scope at
C:\Users\millsjf\.juliapro\JuliaPro_v1.2.0-1\packages\Pumas\0iiH8\src\Pumas.jl:31
 [8] include at .\boot.jl:328 [inlined]
 [9] include_relative(::Module, ::String) at .\loading.jl:1094
 [10] include(::Module, ::String) at .\Base.jl:31
 [11] top-level scope at none:2
 [12] eval at .\boot.jl:330 [inlined]
 [13] eval(::Expr) at .\client.jl:432
 [14] top-level scope at .\none:3
in expression starting at
C:\Users\millsjf\.juliapro\JuliaPro_v1.2.0-1\packages\Pumas\0iiH8\src\estimation\bayes.jl:18
in expression starting at
C:\Users\millsjf\.juliapro\JuliaPro_v1.2.0-1\packages\Pumas\0iiH8\src\Pumas.jl:31
ERROR: Failed to precompile Pumas [4f2c3c20-a4ac-11e9-067b-e5872d3484cf] to
C:\Users\millsjf\.juliapro\JuliaPro_v1.2.0-1\compiled\v1.2\Pumas\OjQAZ.ji.
Stacktrace:
 [1] compilecache(::Base.PkgId, ::String) at .\loading.jl:1253
 [2] _require(::Base.PkgId) at .\loading.jl:1013
 [3] require(::Base.PkgId) at .\loading.jl:911
 [4] require(::Module, ::Symbol) at .\loading.jl:906

julia>

**Comment by andreasnoack** [comment]
So the version you have installed is indeed really old. I'm not sure why you are not getting the latest version when you do `] up Pumas`. Could you please try `] add Pumas@0.8`?

**Comment by tszanalytics** [comment]
Here's what I get with that:

(v1.2) pkg> add Pumas@0.8
  Updating registry at
`C:\Users\millsjf\.juliapro\JuliaPro_v1.2.0-1\registries\JuliaPro`
  Updating git-repo `https://pkg.juliacomputing.com//registry/JuliaPro`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package MCMCChains
[c7f686f2]:
 MCMCChains [c7f686f2] log:
 ├─possible versions are: [0.2.4, 0.3.0-0.3.15, 0.4.0] or uninstalled
 ├─restricted to versions 0.4.0 by an explicit requirement, leaving only
versions 0.4.0
 └─restricted by compatibility requirements with Pumas [4f2c3c20] to
versions: 0.3.11-0.3.15 — no versions left
   └─Pumas [4f2c3c20] log:
     ├─possible versions are: [0.0.7, 0.1.0, 0.2.0, 0.3.1, 0.4.0, 0.5.0,
0.6.0, 0.7.0, 0.8.0] or uninstalled
     └─restricted to versions 0.8 by an explicit requirement, leaving only
versions 0.8.0

**Comment by andreasnoack** [comment]
Could you please try `] free MCMCChains`?

**Comment by tszanalytics** [comment]
(v1.2) pkg> free MCMCChains
  Updating
`C:\Users\millsjf\.juliapro\JuliaPro_v1.2.0-1\environments\v1.2\Project.toml`
 [no changes]
  Updating
`C:\Users\millsjf\.juliapro\JuliaPro_v1.2.0-1\environments\v1.2\Manifest.toml`
 [no changes]

(v1.2) pkg> add Pumas@0.8
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package MCMCChains
[c7f686f2]:
 MCMCChains [c7f686f2] log:
 ├─possible versions are: [0.2.4, 0.3.0-0.3.15, 0.4.0] or uninstalled
 ├─restricted to versions 0.4.0 by an explicit requirement, leaving only
versions 0.4.0
 └─restricted by compatibility requirements with Pumas [4f2c3c20] to
versions: 0.3.11-0.3.15 — no versions left
   └─Pumas [4f2c3c20] log:
     ├─possible versions are: [0.0.7, 0.1.0, 0.2.0, 0.3.1, 0.4.0, 0.5.0,
0.6.0, 0.7.0, 0.8.0] or uninstalled
     └─restricted to versions 0.8 by an explicit requirement, leaving only
versions 0.8.0

**Comment by andreasnoack** [comment]
Okay. The package manager didn't do what I thought it would. Could you then please try `] rm MCMCChains` and then ` ] up Pumas` or `] add Pumas@0.8` if `up` isn't working.

**Comment by tszanalytics** [comment]
Ok, that worked: rm MCMCChains then up Pumas that is.  However, now
MCMCChains is unavailable and I use that frequently.  I will see what
happens when I add MCMCChains again.  Thanks for all the help btw!

**Comment by tszanalytics** [comment]
I added MCMCChains and everything appears to be working fine now (thought
there is conflict between a Turing @model statement and a Pumas one if I
try to do both - not sure what the right syntax is to specify which, but no
worries).  Thanks again for all the help.

**Comment by andreasnoack** [comment]
This is probably a case where you should use two different environments: one for Pumas and one for Turing.
