### ISSUE TITLE
Pre should be initialized by time values that are matching in type.

### ISSUE THREAD

**Issue by ChrisRackauckas** [PumasAI/Pumas.jl#830]
Straightforward from the title. Introduced in https://github.com/PumasAI/Pumas.jl/pull/824 . This `col(0)` (`pre(0)`) call at the start may introduce type-instabilities or cause error if dual numbers and if time is directly used.

**Comment by andreasnoack** [comment]
How would a test case for this look like?

**Comment by ChrisRackauckas** [comment]
Something with `t` used in `pre` so that way it has to be Dual. That is a tough one to find out how to make it error though.

**Comment by pkofod** [comment]
Would the correct type be `eltype(tspan)`?

**Comment by ChrisRackauckas** [comment]
Yes

**Comment by ChrisRackauckas** [comment]
https://github.com/PumasAI/Pumas.jl/pull/805 is handling it because it's tackling some similar things at the same time.

**Comment by pkofod** [comment]
Great
