### ISSUE TITLE
Consider packing actual dvs with the predicted outcomes

### ISSUE THREAD

**Issue by pkofod** [PumasAI/Pumas.jl#863]
When calling `predict` it might be useful to include a copy/reference to the original dvs such that it's easier to compare actual to predicted.

**Comment by jgobburu** [comment]
please also make sure time=0 row is included. Currently, time=0 (evid=1) is excluded from predict() output. Mostly likely observed dv at time=0 will be missing, which should be included as missing in a manner that does not interfere with plotting. However, ipred and pred at time=0 will not be missing.
