### ISSUE TITLE
DataFrame output for NCAReport

### ISSUE THREAD

**Issue by vjd** [PumasAI/Pumas.jl#878]
Currently, it is a two-step process to get the NCAReport as a DataFrame. 

1. `report = NCAReport(ncadata)`
2. `ncareport = NCA.to_dataframe(report)`

We should be able to consolidate this and just have NCAReport output a DataFrame such that the step below gives us a DataFrame

1. `report = NCAReport(ncadata)`

**Comment by pkofod** [comment]
So is the Julia-representation never needed?

**Comment by vjd** [comment]
not unless we are debugging anything. For a normal end-user, no
